language: java
script: mvn flyway:migrate clean install release:update-versions deploy
branches:
  only:
    - master
    - desen
jdk:
  - oraclejdk11
deploy:
  provider: heroku
  app: dindin-app
  access_key_id: $HEROKU_ID
  api_key: $HEROKU_TOKEN
  skip_cleanup: true
  on:
    repo: renanravelli/dindin-app
    branch: desen
notifications:
  email: false
cache:
  directories:
    - $HOME/.m2
