spring:
  datasource:
    url: ${DINDINSOUZA_DATABASE_URL}
    username: ${DINDINSOUZA_DATABASE_USERNAME}
    password: ${DINDINSOUZA_DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: false
    properties:
      hibernate:
        default_schema: @flyway.schemas@
    hibernate:
      ddl-auto: none
jwt:
  secret: secret
  expiration: 2629746000
server:
  servlet:
    context-path: /api

storage: /tmp/storage
