CREATE SCHEMA IF NOT EXISTS ${schema};

CREATE TABLE IF NOT EXISTS ${schema}.TB_SOLICITACAO
(
    ID               SERIAL,
    ID_INFORMACAO    BIGINT        NOT NULL,
    ID_ESTOQUE       BIGINT        NOT NULL,
    QUANTIDADE       INTEGER       NOT NULL,
    VALOR_TOTAL      DECIMAL(6, 2) NOT NULL,
    FORMA_PAGAMENTO  VARCHAR(30),
    DATA_SOLICITACAO TIMESTAMP     NOT NULL DEFAULT NOW(),
    DATA_ENTREGA     TIMESTAMP,
    DATA_PAGAMENTO   TIMESTAMP,
    STATUS           VARCHAR(30)   NOT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (ID_INFORMACAO) REFERENCES ${schema}.TB_INFORMACAO (ID),
    FOREIGN KEY (ID_ESTOQUE) REFERENCES ${schema}.TB_ESTOQUE (ID)
);
